### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by tune6688** [RadiantSystem/radiant#1]
Dear writer:

After the installation is complete, run installer.pl then show "500 Internal Server Error".
err log as below:

> [Mon Mar 29 17:05:46.758110 2021] [suexec:notice] [pid 5970] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
> AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive globally to suppress this message
> [Mon Mar 29 17:05:47.093761 2021] [lbmethod_heartbeat:notice] [pid 5970] AH02282: No slotmem from mod_heartmonitor
> [Mon Mar 29 17:05:47.102744 2021] [mpm_prefork:notice] [pid 5970] AH00163: Apache/2.4.6 (CentOS) mod_perl/2.0.11 Perl/v5.16.3 configured -- resuming normal operations
> [Mon Mar 29 17:05:47.102794 2021] [core:notice] [pid 5970] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
> [Mon Mar 29 17:05:55 2021] -e: DBI connect('database=otrs;host=127.0.0.1;','otrs',...) failed: Access denied for user 'otrs'@'localhost' (using password: YES) at /opt/otrs//Kernel/System/DB.pm line 204.
> [Mon Mar 29 17:05:55.177076 2021] [:error] [pid 5972] [Mon Mar 29 17:05:55 2021] -e: Can't load log backend module Kernel::System::Log::SysLog! Can't locate Sys/Syslog.pm in @INC (@INC contains: /usr/Custom /usr/Kernel/cpan-lib /usr /usr/sbin/../../Custom /usr/sbin/../../Kernel/cpan-lib /usr/sbin/../.. /opt/otrs/Custom /opt/otrs/Kernel/cpan-lib /opt/otrs/ /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /etc/httpd) at /opt/otrs//Kernel/System/Log/SysLog.pm line 14.\n[Mon Mar 29 17:05:55 2021] -e: BEGIN failed--compilation aborted at /opt/otrs//Kernel/System/Log/SysLog.pm line 14.\n[Mon Mar 29 17:05:55 2021] -e: Compilation failed in require at (eval 487) line 2.\n

OS: [centos7]
Browser: [ Chrome, Firefox]

Please give me some advice on how to solve it
Thank you very much！

**Comment by kozachkov** [comment]
> Can't locate Sys/Syslog.pm

That's not a bug, it says that on your CentOS7 system there is no perl **Sys::Syslog** module and it is strange because it is delivered with perl itself since 5 version. What perl version do you use?

Add `perl -E 'say "$^V\n".join("\n", @INC)'` output here
and also output for this command: `perl -MSys::Syslog -E 'say $^V'`

For quick fixing you can install the mixing perl module with this command:
`# yum install 'perl(Sys::Syslog)'` or with this one `# cpanm Sys::Syslog` (`yum install cpanminus` must be run before you can use  cpanm).

**Comment by tune6688** [comment]
Thank you for your kind reply.I used your method, the problem is the same.
err log as below:

> [Tue Mar 30 09:48:31.481068 2021] [suexec:notice] [pid 3865] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
> AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive globally to suppress this message
> [Tue Mar 30 09:48:31.810303 2021] [lbmethod_heartbeat:notice] [pid 3865] AH02282: No slotmem from mod_heartmonitor
> [Tue Mar 30 09:48:31.820056 2021] [mpm_prefork:notice] [pid 3865] AH00163: Apache/2.4.6 (CentOS) mod_perl/2.0.11 Perl/v5.16.3 configured -- resuming normal operations
> [Tue Mar 30 09:48:31.820108 2021] [core:notice] [pid 3865] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
> [Tue Mar 30 09:48:36 2021] -e: DBI connect('database=otrs;host=127.0.0.1;','otrs',...) failed: Access denied for user 'otrs'@'localhost' (using password: YES) at /opt/otrs//Kernel/System/DB.pm line 204.
> [Tue Mar 30 09:48:36.328193 2021] [:error] [pid 3866] [Tue Mar 30 09:48:36 2021] -e: Can't load log backend module Kernel::System::Log::SysLog! Can't locate Sys/Syslog.pm in @INC (@INC contains: /usr/Custom /usr/Kernel/cpan-lib /usr /usr/sbin/../../Custom /usr/sbin/../../Kernel/cpan-lib /usr/sbin/../.. /opt/otrs/Custom /opt/otrs/Kernel/cpan-lib /opt/otrs/ /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /etc/httpd) at /opt/otrs//Kernel/System/Log/SysLog.pm line 14.\n[Tue Mar 30 09:48:36 2021] -e: BEGIN failed--compilation aborted at /opt/otrs//Kernel/System/Log/SysLog.pm line 14.\n[Tue Mar 30 09:48:36 2021] -e: Compilation failed in require at (eval 432) line 2.

Can you give me some more advice?
I really appreciate your help!

**Comment by kozachkov** [comment]
@tune6688 add `perl -E 'say "$^V\n".join("\n", @INC)'` output here and also output for this command: `perl -MSys::Syslog -E 'say $^V'`

**Comment by tune6688** [comment]
Dear kmhl
[root@localhost ~]# perl -MSys::Syslog -E 'say $^V'
v5.16.3.
BTW: I see that Radiant is the fork of ((OTRS)) Community Edition,how is this version different from otrs?

Thank you for your help!

**Comment by kozachkov** [comment]
> [root@localhost ~]# perl -MSys::Syslog -E 'say $^V'
> v5.16.3.

It says that Sys::Syslog is installed on your system with perl so the problem with @INC paths to the perl modules.

Add the output from this command: `perl -E 'say "$^V\n".join("\n", @INC)'` (I asked you about it third time, it's safe command don't worry). And also run this command `perl -MSys::Syslog -E 'say $INC{"Sys/Syslog.pm"}'` and add its output too.

> I see that Radiant is the fork of ((OTRS)) Community Edition,how is this version different from otrs?

By this moment they are the same. The changes between them will be added to Release descriptions and to the CHANGES file.

**Comment by tune6688** [comment]
Fixed.Your help was very much appreciated.

**Comment by kozachkov** [comment]
> Fixed.Your help was very much appreciated.

@tune6688 that's good. How did you fix it?

**Comment by tune6688** [comment]
Run cpanm Sys::Syslog does not solve the problem.
Run yum install 'perl(Sys::Syslog) to fix it.
